table Dim_DynamicMetricControls
	lineageTag: e8a78bf1-bc8c-47ff-b883-9b65d1d6a999

	measure Selected_Executive_Metric_Value = 
			VAR CurrentSelection = SELECTEDVALUE(Dim_DynamicMetricControls[MetricName], "Total AUM")
			RETURN
				SWITCH(
					CurrentSelection,
					"Total AUM", [Total_AUM_ZAR],
					"YTD Return", [Weighted_Portfolio_Return_Percent],
					"PFMA Variances", [PFMA_Irregular_Expenditure_Counter],
					[Total_AUM_ZAR]
				)

	column MetricKey
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: [MetricKey]

	column MetricName
		dataType: string
		summarizeBy: none
		sourceColumn: [MetricName]

	column MetricDisplayOrder
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: [MetricDisplayOrder]

	partition Dim_DynamicMetricControls = calculated
		mode: import
		source = DATATABLE("MetricKey", INTEGER, "MetricName", STRING, "MetricDisplayOrder", INTEGER, { {1, "Total AUM", 1}, {2, "YTD Return", 2}, {3, "PFMA Variances", 3}, {4, "Tracking Error", 4}, {5, "Sharpe Ratio", 5} })