table Fact_FinancialTransactions
	lineageTag: 2c6259df-a182-4fc9-b4fe-40d9a608ecc0
	sourceLineageTag: 7f20c669-768b-48c3-bd56-c3492a6a94da










	measure Total_Actual_Amount = SUM(Fact_FinancialTransactions[ActualAmount])
		formatString: R#,##0.00;"(R#,##0.00)";"-"

	measure Total_Budget_Amount = SUM(Fact_FinancialTransactions[BudgetAmount])
		formatString: R#,##0.00;"(R#,##0.00)";"-"

	measure Budget_vs_Actual_Variance_Percent = DIVIDE([Total_Actual_Amount] - [Total_Budget_Amount], [Total_Budget_Amount])
		formatString: 0.00%

	measure YoY_Actual_Opex_Variance_Percent =
			VAR ActualYTD = TOTALYTD([Total_Actual_Amount], Dim_Date[Date])
			VAR PriorYTD = TOTALYTD([Total_Actual_Amount], DATEADD(Dim_Date[Date], -1, YEAR))
			RETURN DIVIDE(ActualYTD - PriorYTD, PriorYTD)
		formatString: 0.00%

	measure PFMA_Irregular_Expenditure_Counter = CALCULATE(COUNTROWS(Fact_FinancialTransactions), Fact_FinancialTransactions[PFMA_Status_Code] > 0)
		formatString: #,##0

	measure Opex_YoY_Variance_Percent =
			VAR CurrentYTD = TOTALYTD(SUM(Fact_FinancialTransactions[ActualAmount]), Dim_Date[Date])
			VAR PriorYTD = TOTALYTD(SUM(Fact_FinancialTransactions[ActualAmount]), DATEADD(Dim_Date[Date], -1, YEAR))
			VAR VarianceValue = CurrentYTD - PriorYTD
			RETURN
				DIVIDE(
					VarianceValue, 
					PriorYTD, 
					0
				)
		formatString: 0.00%

	measure Rolling_12Month_Opex =
			VAR EndDate = MAX(Dim_Date[Date])
			VAR StartDate = EDATE(EndDate, -12) + 1
			VAR CalculationPeriod = 
				FILTER(
					ALL(Dim_Date),
					Dim_Date[Date] >= StartDate && 
					Dim_Date[Date] <= EndDate
				)
			RETURN
				CALCULATE(
					SUM(Fact_FinancialTransactions[ActualAmount]),
					CalculationPeriod
				)
		formatString: R#,##0.00;"(R#,##0.00)";"-"

	measure Division_Expenditure_Share_Percent =
			VAR SelectedDivisionSpend = SUM(Fact_FinancialTransactions[ActualAmount])
			VAR TotalCorporateSpend = 
				CALCULATE(
					SUM(Fact_FinancialTransactions[ActualAmount]),
					ALLSELECTED(Dim_Division)
				)
			RETURN
				DIVIDE(
					SelectedDivisionSpend, 
					TotalCorporateSpend, 
					0
				)
		formatString: 0.00%

	measure Cost_to_Income_Ratio =
			VAR TotalIncome = SUMX(Fact_PortfolioReturns, Fact_PortfolioReturns[MarketValue] * 0.0015)
			RETURN
				DIVIDE(
					SUM(Fact_FinancialTransactions[ActualAmount]),
					TotalIncome,
					0
				)
		formatString: 0.00%
	column TransactionKey
		dataType: int64
		formatString: 0
		lineageTag: 01972240-553e-457a-b0b3-c0cd230e2bd8
		sourceLineageTag: 57be3ab3-3a36-4ab0-98d9-3ba1fa457972
		dataCategory: Uncategorized
		summarizeBy: count
		sourceColumn: TransactionKey

		annotation SummarizationSetBy = User

	column DateKey
		dataType: int64
		formatString: 0
		lineageTag: 6fcddffc-1450-443a-83e9-6fcb4d86068b
		sourceLineageTag: 92edf93b-84e9-499f-8733-c8c4b11f0d4b
		dataCategory: Uncategorized
		summarizeBy: count
		sourceColumn: DateKey

		annotation SummarizationSetBy = User

	column DivisionKey
		dataType: int64
		formatString: 0
		lineageTag: a7bbbbfb-9137-419e-a231-52910d802f26
		sourceLineageTag: 75e17102-211a-46fb-b524-976e32080c16
		dataCategory: Uncategorized
		summarizeBy: count
		sourceColumn: DivisionKey

		annotation SummarizationSetBy = User

	column AccountCode
		dataType: int64
		formatString: 0
		lineageTag: 87f27662-5ccc-43ae-9227-f6485cfdec07
		sourceLineageTag: da7aa6cb-aa53-4a8c-a121-c6755601e0d4
		dataCategory: Uncategorized
		summarizeBy: count
		sourceColumn: AccountCode

		annotation SummarizationSetBy = User

	column ActualAmount
		dataType: double
		lineageTag: 91689cfb-9acf-4f1a-bbef-789cdd83bc7b
		sourceLineageTag: 52de1f24-c202-433d-bba2-583383394c1e
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: ActualAmount

		annotation SummarizationSetBy = User

	column BudgetAmount
		dataType: double
		lineageTag: 76b7d3db-a822-43c9-abfe-c27498716134
		sourceLineageTag: 8b56ac34-1e3a-4d57-a2c7-20011f0a4b73
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: BudgetAmount

		annotation SummarizationSetBy = User

	column PFMA_Status_Code
		dataType: int64
		formatString: 0
		lineageTag: ede9082c-c7df-4095-91eb-6995fd84257f
		sourceLineageTag: 4720f3b8-acda-4469-901d-24bb2a092ce1
		dataCategory: Uncategorized
		summarizeBy: count
		sourceColumn: PFMA_Status_Code

		annotation SummarizationSetBy = User

	column Last_Modified_Timestamp
		dataType: dateTime
		formatString: General Number
		lineageTag: 23f7cdec-5266-44a0-973e-4ab7a4658147
		sourceLineageTag: ef174824-bf8c-4469-9549-5075e211dc39
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Last_Modified_Timestamp

		annotation SummarizationSetBy = User

	partition Fact_FinancialTransactions = entity
		mode: directQuery
		source
			entityName: Fact_FinancialTransactions
			expressionSource: 'DirectQuery to AS - investment_public'
