table Fact_HREvents
	lineageTag: ea13bf22-ae8a-479f-95b6-8af1287d690a
	sourceLineageTag: dfb5b26a-052d-4d83-af06-751a3090524d






	measure Active_Staff_Headcount =
			VAR MaxDateInContext = MAX(Dim_Date[Date])
			RETURN
				CALCULATE(
					DISTINCTCOUNT(Fact_HREvents[EmployeeKey]),
					Fact_HREvents[EventTypeName] = "Active Snapshot",
					Dim_Date[Date] = MaxDateInContext
				)
		formatString: #,##0

	measure Training_Spend = SUM(Fact_HREvents[TrainingSpend])
		formatString: R#,##0.00;"(R#,##0.00)";"-"

	measure Annualized_Turnover_Percent =
			VAR ExitCount = CALCULATE(COUNTROWS(Fact_HREvents), Fact_HREvents[EventTypeName] = "Exit")
			VAR AvgHeadcount = AVERAGEX(VALUES(Dim_Date[DateKey]), [Active_Staff_Headcount])
			RETURN
				DIVIDE(ExitCount, AvgHeadcount, 0)
		formatString: 0.00%

	measure EE_Alignment_Score =
			VAR HDIHeadcount = CALCULATE([Active_Staff_Headcount], Dim_Employee[IsHDI] = TRUE)
			VAR TotalHeadcount = [Active_Staff_Headcount]
			RETURN
				DIVIDE(HDIHeadcount, TotalHeadcount, 0)
		formatString: 0.00%

	measure Skills_Development_Spend_Percent =
			DIVIDE(
				SUM(Fact_HREvents[TrainingSpend]), 
				SUM(Dim_Employee[SalaryAmount]), 
				0
			)
		formatString: 0.00%
	column HREventKey
		dataType: int64
		formatString: 0
		lineageTag: 4f1bc435-2fc5-456b-b25d-948d01b83c98
		sourceLineageTag: 89512175-1df7-4434-834f-60834fe1c2ba
		dataCategory: Uncategorized
		summarizeBy: count
		sourceColumn: HREventKey

		annotation SummarizationSetBy = User

	column DateKey
		dataType: int64
		formatString: 0
		lineageTag: 81f75a09-f70f-43b1-bf7e-977f57ee1115
		sourceLineageTag: cef2b52c-1967-4a67-8f78-33240d3299ba
		dataCategory: Uncategorized
		summarizeBy: count
		sourceColumn: DateKey

		annotation SummarizationSetBy = User

	column EmployeeKey
		dataType: int64
		formatString: 0
		lineageTag: 912fca42-2ca8-467e-98b9-16a656a83315
		sourceLineageTag: 80b38baa-698f-4008-a719-74d868a845d9
		dataCategory: Uncategorized
		summarizeBy: count
		sourceColumn: EmployeeKey

		annotation SummarizationSetBy = User

	column DivisionKey
		dataType: int64
		formatString: 0
		lineageTag: 71c0b88e-78c5-4322-afea-875b31db9f01
		sourceLineageTag: f5b3c7a3-fd4b-4d87-903c-1ae53a3a8eb0
		dataCategory: Uncategorized
		summarizeBy: count
		sourceColumn: DivisionKey

		annotation SummarizationSetBy = User

	column EventTypeName
		dataType: string
		lineageTag: 28421402-deef-4546-b606-047842eb9600
		sourceLineageTag: ff7169ba-4786-4e4f-87c7-ca75cab3e2e6
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: EventTypeName

		annotation SummarizationSetBy = User

	column TrainingSpend
		dataType: double
		lineageTag: 8ee59bc0-a364-43cd-9509-152b4e4113b2
		sourceLineageTag: bd79aefa-e9b9-4e3e-ae42-78f6d7c1d1eb
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: TrainingSpend

		annotation SummarizationSetBy = User

	partition Fact_HREvents = entity
		mode: directQuery
		source
			entityName: Fact_HREvents
			expressionSource: 'DirectQuery to AS - investment_public'
