table Fact_PortfolioReturns
	lineageTag: a922264d-46cc-4c1e-9c2d-5f9d6d1f814a
	sourceLineageTag: 59f88d75-99de-4396-9f26-0bd5df323a0e






	measure Total_Market_Value = SUM(Fact_PortfolioReturns[MarketValue])
		formatString: R#,##0.00;"(R#,##0.00)";"-"

	measure Portfolio_Return = DIVIDE(SUMX(Fact_PortfolioReturns, Fact_PortfolioReturns[DailyReturn] * Fact_PortfolioReturns[MarketValue]), [Total_Market_Value])
		formatString: 0.00%

	measure Total_AUM_ZAR = SUM(Fact_PortfolioReturns[MarketValue])
		formatString: R#,##0.00;"(R#,##0.00)";"-"

	measure Weighted_Portfolio_Return_Percent =
			DIVIDE(
				SUMX(Fact_PortfolioReturns, Fact_PortfolioReturns[DailyReturn] * Fact_PortfolioReturns[MarketValue]), 
				[Total_Market_Value], 
				0
			)
		formatString: 0.00%

	measure Portfolio_Tracking_Error_Percent =
			VAR MeanExcessReturn = 
				AVERAGEX(
					Fact_PortfolioReturns,
					Fact_PortfolioReturns[DailyReturn] - Fact_PortfolioReturns[DailyBenchmarkReturn]
				)
			VAR ExcessReturnVarianceIter = 
				SUMX(
					Fact_PortfolioReturns,
					POWER(
						(Fact_PortfolioReturns[DailyReturn] - Fact_PortfolioReturns[DailyBenchmarkReturn]) - MeanExcessReturn, 
						2
					)
				)
			VAR TotalObservedDays = COUNTROWS(Fact_PortfolioReturns)
			VAR DailyTrackingError = 
				SQRT(
					DIVIDE(
						ExcessReturnVarianceIter, 
						TotalObservedDays - 1, 
						0
					)
				)
			RETURN
				DailyTrackingError * SQRT(252)
		formatString: 0.00%

	measure Sharpe_Ratio =
			VAR RiskFreeRate = 0.05 / 252
			VAR DailyExcessReturn = Fact_PortfolioReturns[DailyReturn] - RiskFreeRate
			VAR AvgExcessReturn = AVERAGEX(Fact_PortfolioReturns, DailyExcessReturn)
			VAR StdDevReturn = STDEVX.S(Fact_PortfolioReturns, Fact_PortfolioReturns[DailyReturn])
			RETURN
				DIVIDE(AvgExcessReturn, StdDevReturn, 0) * SQRT(252)
		formatString: 0.00

	measure VaR_95_1Day =
			VAR MeanReturn = AVERAGEX(Fact_PortfolioReturns, Fact_PortfolioReturns[DailyReturn])
			VAR StdDevReturn = STDEVX.S(Fact_PortfolioReturns, Fact_PortfolioReturns[DailyReturn])
			RETURN
				-1 * (MeanReturn - 1.645 * StdDevReturn)
		formatString: 0.00%

	measure Information_Ratio =
			VAR ActiveReturn = 
				AVERAGEX(
					Fact_PortfolioReturns, 
					Fact_PortfolioReturns[DailyReturn] - Fact_PortfolioReturns[DailyBenchmarkReturn]
				) * 252
			VAR TrackingError = [Portfolio_Tracking_Error_Percent]
			RETURN
				DIVIDE(ActiveReturn, TrackingError, 0)
		formatString: 0.00

	measure Mandate_Breach_Count =
			CALCULATE(
				COUNTROWS(Fact_PortfolioReturns), 
				ABS(Fact_PortfolioReturns[DailyReturn] - Fact_PortfolioReturns[DailyBenchmarkReturn]) > 0.02
			)
		formatString: #,##0

	measure Portfolio_Average_ESG_Score =
			DIVIDE(
				SUMX(Fact_PortfolioReturns, RELATED(Dim_InvestmentAsset[ESG_Score]) * Fact_PortfolioReturns[MarketValue]), 
				[Total_Market_Value], 
				0
			)
		formatString: 0.0
	column ReturnKey
		dataType: int64
		formatString: 0
		lineageTag: f6b9dd58-250d-4ab4-9308-de5bf397fdb3
		sourceLineageTag: 11b084f9-3474-4e8e-b48c-f4a473676d94
		dataCategory: Uncategorized
		summarizeBy: count
		sourceColumn: ReturnKey

		annotation SummarizationSetBy = User

	column DateKey
		dataType: int64
		formatString: 0
		lineageTag: 24210a5a-37b4-4886-9aaa-5ea39bf0734f
		sourceLineageTag: d6915c6b-7478-4bd2-89a5-2d699be9ac11
		dataCategory: Uncategorized
		summarizeBy: count
		sourceColumn: DateKey

		annotation SummarizationSetBy = User

	column AssetKey
		dataType: int64
		formatString: 0
		lineageTag: b92b62ef-f658-44ba-ba61-4fec0244d1b2
		sourceLineageTag: 7d1782e1-2c2b-4983-a583-6354f9afefef
		dataCategory: Uncategorized
		summarizeBy: count
		sourceColumn: AssetKey

		annotation SummarizationSetBy = User

	column FundKey
		dataType: int64
		formatString: 0
		lineageTag: 1a64be90-8299-4862-83af-fa2173d28632
		sourceLineageTag: 04779368-43d1-414a-99a0-0e2bc53e4470
		dataCategory: Uncategorized
		summarizeBy: count
		sourceColumn: FundKey

		annotation SummarizationSetBy = User

	column DailyReturn
		dataType: double
		lineageTag: 8dd95f22-e41c-4f63-aaf3-051cdd3b53cb
		sourceLineageTag: aac1b453-55fe-4253-ae37-f1036262d57e
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: DailyReturn

		annotation SummarizationSetBy = User

	column DailyBenchmarkReturn
		dataType: double
		lineageTag: e0f2fa66-d233-4fe8-9567-a510ee7cf4dc
		sourceLineageTag: 00d55114-3f92-409d-9a0a-faa8fc47aa19
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: DailyBenchmarkReturn

		annotation SummarizationSetBy = User

	column MarketValue
		dataType: double
		lineageTag: 1a04ab51-e3da-4825-8886-1558dcc6764f
		sourceLineageTag: 7986a7c1-e2fe-43a7-a758-d2826610b918
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: MarketValue

		annotation SummarizationSetBy = User

	partition Fact_PortfolioReturns = entity
		mode: directQuery
		source
			entityName: Fact_PortfolioReturns
			expressionSource: 'DirectQuery to AS - investment_public'
