table Fact_HelpdeskTickets
	lineageTag: 08ab0474-7f92-4254-920a-e0f71e2431b4
	sourceLineageTag: 15b27945-9151-4398-bc39-e246358f086e


	measure System_Availability_Percent =
			VAR TotalDowntimeMinutes = CALCULATE(SUM(Fact_HelpdeskTickets[ResolutionDurationMinutes]), Fact_HelpdeskTickets[PriorityCode] = 1)
			VAR TotalMinutesInPeriod = COUNTROWS(Dim_Date) * 1440
			RETURN
				1 - DIVIDE(TotalDowntimeMinutes, TotalMinutesInPeriod, 0)
		formatString: 0.00%

	measure Data_Quality_Index =
			VAR FinancialCompliance = DIVIDE(CALCULATE(COUNTROWS(Fact_FinancialTransactions), Fact_FinancialTransactions[PFMA_Status_Code] = 0), COUNTROWS(Fact_FinancialTransactions), 0)
			VAR TradeSettlementRate = 1 - [Trade_Settlement_Failure_Rate]
			VAR SLACompliance = [Helpdesk_SLA_Resolution_Percent]
			RETURN
				(FinancialCompliance + TradeSettlementRate + SLACompliance) / 3
		formatString: 0.00%

	measure Helpdesk_SLA_Resolution_Percent =
			DIVIDE(
				CALCULATE(COUNTROWS(Fact_HelpdeskTickets), Fact_HelpdeskTickets[SLA_Met] = TRUE), 
				COUNTROWS(Fact_HelpdeskTickets), 
				0
			)
		formatString: 0.00%
	column TicketKey
		dataType: int64
		formatString: 0
		lineageTag: 39adfd07-2355-48b5-8f09-f6a7b76e09e2
		sourceLineageTag: e0d53c9e-d888-4609-ba76-65c293dbcc3a
		dataCategory: Uncategorized
		summarizeBy: count
		sourceColumn: TicketKey

		annotation SummarizationSetBy = User

	column CreatedDateKey
		dataType: int64
		formatString: 0
		lineageTag: 591f8d8c-5ec4-48f5-bead-d124b98cec05
		sourceLineageTag: 8b0d4e72-33f1-445c-8deb-961f9e25b48a
		dataCategory: Uncategorized
		summarizeBy: count
		sourceColumn: CreatedDateKey

		annotation SummarizationSetBy = User

	column ClosedDateKey
		dataType: int64
		formatString: 0
		lineageTag: 842f11c6-b04f-4137-b63a-779bbba9924b
		sourceLineageTag: 01d713da-1bfb-4ca0-b586-ad0b2136e4bc
		dataCategory: Uncategorized
		summarizeBy: count
		sourceColumn: ClosedDateKey

		annotation SummarizationSetBy = User

	column EmployeeKey
		dataType: int64
		formatString: 0
		lineageTag: 1e5654a1-72dd-431c-a474-99b35df18342
		sourceLineageTag: 5527d441-06d7-4e8f-b649-68227e9c3d32
		dataCategory: Uncategorized
		summarizeBy: count
		sourceColumn: EmployeeKey

		annotation SummarizationSetBy = User

	column PriorityCode
		dataType: int64
		formatString: 0
		lineageTag: ae2e1246-e211-454c-9e9a-2982b0b7f9c7
		sourceLineageTag: c4c2c0be-2738-4a57-8134-194e3e10c8d3
		dataCategory: Uncategorized
		summarizeBy: count
		sourceColumn: PriorityCode

		annotation SummarizationSetBy = User

	column ResolutionDurationMinutes
		dataType: int64
		formatString: 0
		lineageTag: 2f61151f-acdb-4a8b-a238-cbba2ee517e3
		sourceLineageTag: 05e0581a-d9db-4f3d-8b11-abb9a64e8e24
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: ResolutionDurationMinutes

		annotation SummarizationSetBy = User

	column SLA_Met
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 233a0a7e-d2ea-492c-a4a9-c7a96cc92dab
		sourceLineageTag: 43ab93a8-da0e-4b84-a162-b637874dce05
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: SLA_Met

		annotation SummarizationSetBy = User

	partition Fact_HelpdeskTickets = entity
		mode: directQuery
		source
			entityName: Fact_HelpdeskTickets
			expressionSource: 'DirectQuery to AS - investment_public'
