table Fact_UnlistedInvestments
	lineageTag: eccab6ac-f5f2-4bfb-a1c3-f525d6496047
	sourceLineageTag: 7b05eb13-4e7c-46a9-bd16-3530762c6981




	measure Total_Net_Asset_Value = SUM(Fact_UnlistedInvestments[NetAssetValue])
		formatString: R#,##0.00;"(R#,##0.00)";"-"

	measure Private_Equity_IRR_Approximation =
			VAR CashFlowTable = 
				SELECTCOLUMNS(
					Fact_UnlistedInvestments,
					"CF_Date", RELATED(Dim_Date[Date]),
					"CF_Amount", Fact_UnlistedInvestments[CashFlowAmount]
				)
			RETURN
				XIRR(
					CashFlowTable, 
					[CF_Amount], 
					[CF_Date]
				)
		formatString: 0.00%

	measure MOIC =
			VAR TotalDistributions = CALCULATE(SUM(Fact_UnlistedInvestments[CashFlowAmount]), Fact_UnlistedInvestments[TransactionType] = "Distribution")
			VAR TotalDrawdowns = -1 * CALCULATE(SUM(Fact_UnlistedInvestments[CashFlowAmount]), Fact_UnlistedInvestments[TransactionType] = "Drawdown")
			VAR CurrentNAV = CALCULATE(SUM(Fact_UnlistedInvestments[NetAssetValue]), Fact_UnlistedInvestments[TransactionType] = "Valuation")
			RETURN
				DIVIDE(TotalDistributions + CurrentNAV, TotalDrawdowns, 0)
		formatString: 0.00"x"

	measure DPI =
			VAR TotalDistributions = CALCULATE(SUM(Fact_UnlistedInvestments[CashFlowAmount]), Fact_UnlistedInvestments[TransactionType] = "Distribution")
			VAR TotalDrawdowns = -1 * CALCULATE(SUM(Fact_UnlistedInvestments[CashFlowAmount]), Fact_UnlistedInvestments[TransactionType] = "Drawdown")
			RETURN
				DIVIDE(TotalDistributions, TotalDrawdowns, 0)
		formatString: 0.00"x"
	column UnlistedTransactionKey
		dataType: int64
		formatString: 0
		lineageTag: 6ba57cb7-2ec8-43f5-a190-bf48e9d6acf4
		sourceLineageTag: edf283da-8a6f-494d-b8bc-7c25d00c5bf4
		dataCategory: Uncategorized
		summarizeBy: count
		sourceColumn: UnlistedTransactionKey

		annotation SummarizationSetBy = User

	column DateKey
		dataType: int64
		formatString: 0
		lineageTag: 54e1fd96-50b2-412d-9308-05a692f59856
		sourceLineageTag: 22099b53-110d-4c53-8b28-7d508c4d398c
		dataCategory: Uncategorized
		summarizeBy: count
		sourceColumn: DateKey

		annotation SummarizationSetBy = User

	column AssetKey
		dataType: int64
		formatString: 0
		lineageTag: f76d2008-637d-47e0-bab2-8ea22ca8fd5d
		sourceLineageTag: 4915e07a-eec3-4f0a-a8c7-029a1be904fd
		dataCategory: Uncategorized
		summarizeBy: count
		sourceColumn: AssetKey

		annotation SummarizationSetBy = User

	column FundKey
		dataType: int64
		formatString: 0
		lineageTag: 2c7db11e-8dd7-4445-9fce-005046888c53
		sourceLineageTag: 9feb60a7-fb08-4484-9661-b976b617d380
		dataCategory: Uncategorized
		summarizeBy: count
		sourceColumn: FundKey

		annotation SummarizationSetBy = User

	column TransactionType
		dataType: string
		lineageTag: 0a8950b1-32f1-4890-ba02-27d76c22a90d
		sourceLineageTag: 30f20a68-b12d-4534-bc91-0d18e7cbcd1b
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: TransactionType

		annotation SummarizationSetBy = User

	column CashFlowAmount
		dataType: double
		lineageTag: 66d0e14c-8d46-4040-9a5e-501c59f3e7b9
		sourceLineageTag: c9efc9d2-6d4d-4ac1-94a0-4788a2992a28
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: CashFlowAmount

		annotation SummarizationSetBy = User

	column NetAssetValue
		dataType: double
		lineageTag: 76a645d2-b0c3-4b65-869e-1538ec9cb678
		sourceLineageTag: a74d2e44-ae75-4e48-b7de-127b0950ce68
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: NetAssetValue

		annotation SummarizationSetBy = User

	partition Fact_UnlistedInvestments = entity
		mode: directQuery
		source
			entityName: Fact_UnlistedInvestments
			expressionSource: 'DirectQuery to AS - investment_public'
